# Generated by Django 2.0.7 on 2018-10-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
