# Generated by Django 2.0.7 on 2018-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbase',
            name='Ext',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
